# Generated by Django 5.0.3 on 2024-04-05 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proptEz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('cover_image', models.TextField()),
                ('pg_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_contact', models.PositiveBigIntegerField()),
                ('dist_f_college', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pin_code', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('d_name', models.CharField(max_length=15)),
                ('order_by', models.PositiveIntegerField(default=0)),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proptEz.dropdown')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomAvialable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('room_images', models.JSONField()),
                ('seater', models.PositiveSmallIntegerField()),
                ('price_p_month', models.FloatField()),
                ('no_of_avlroom', models.PositiveSmallIntegerField()),
                ('facilities_avl', models.JSONField()),
                ('description', models.TextField(max_length=200)),
                ('pg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_pg', to='proptEz.pgdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
